name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Cambia esto si usas una rama diferente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install
      working-directory: frontend  # Cambia esto si es necesario

    - name: Build project
      run: npm run build
      working-directory: frontend  # Cambia esto si es necesario

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./frontend  # Cambia esto a la carpeta de despliegue correcta
